workerStark: node stark_bot.js
workerStark2: node stark_bot2.js
workerStark3: node stark_bot3.js
workerStark4: node stark_bot4.js
workerStark5: node stark_bot5.js
workerStark6: node stark_bot6.js
workerStark7: node stark_bot7.js
workerStark8: node stark_bot8.js
workerStark9: node stark_bot9.js
workerStark10: node stark_bot10.js
workerStark11: node stark_bot11.js
workerStark12: node stark_bot12.js
workerStark13: node stark_bot13.js
workerStark14: node stark_bot14.js
workerStark15: node stark_bot15.js
workerDiscrim: node tag1.js
workerDiscrim2: node tag2.js
workerDiscrim3: node tag3.js
workerDiscrim4: node tag4.js
workerDiscrim5: node tag5.js
workerDiscrim6: node tag6.js
workerDiscrim7: node tag7.js
workerDiscrim8: node tag8.js
workerDiscrim9: node tag9.js
workerDiscrim10: node tag10.js
workerstarkad1: node stark_ad.js
workerstarkad2: node stark_ad2.js
workerorderad1: node order_ad1.js
workerorderad2: node order_ad2.js
workerorderad3: node order_ad3.js
workerorderad4: node order_ad4.js
workerorderad5: node order_ad5.js
workerorderad6: node order_ad6.js
workerorderad7: node order_ad7.js
workerorderad8: node order_ad8.js
workerStatus: node status.js
worker: node bot.js
worker1a: node discord_anti_spam.js
worker1: node bot1.js
worker3: node tjme3_1.js
worker4: node tjme3_2.js
worker5: node tjme3_3.js
worker6: node tjme3_4.js
worker7: node tjme3_5.js
worker8: node tjme3_6.js
worker9: node tjme3_7.js
worker10t: node tjme3_8.js
worker11t: node tjme3_9.js
worker12t: node tjme3_10.js
worker55: node role.js
worker56: node vb.js
worker57: node bankick.js
worker59: node recrownd.js
worker60: node recrownd1.js
worker67: node tjme3_11.js
worker68: node tjme3_12.js
worker69: node tjme3_13.js
worker70: node tjme3_14.js
worker71: node tjme3_15.js
worker72: node tjme3_16.js
worker73: node tjme3_17.js
worker74: node tjme3_18.js
worker75: node tjme3_19.js
worker76: node tjme3_20.js
worker77: node users_welcome.js
