worker: node bot.js
worker1: node bot1.js
worker2: node quran.js
worker3: node bot2.js
worker4: node bot3.js
worker5: node bot4.js
worker6: node bot5.js
worker7: node bot6.js
worker49: node help.js
worker50: node bc.js
worker51: node move.js
worker52: node mute.js
worker53: node channels.js
worker54: node realbot.js
worker55: node role.js
worker56: node vb.js
